### ISSUE TITLE
Cannot find module 'detective'

### ISSUE THREAD

**Issue by ghost** [Zemke/starter-laravel-angular#34]
$ gulp
module.js:339
    throw err;
    ^

Error: Cannot find module 'detective'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Aios\laradock\laravel\node_modules\laravel-elixir\node_modules\browserify\node_modules\module-deps\index.js:6:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

**Comment by Zemke** [comment]
I would try

``` sh
npm cache clean
rm -rf node_modules
npm install
gulp
```

**Comment by ghost** [comment]
Solved, upgrading nodejs to 5.4.8 with npm 3.3.2
or

``` bash
npm install -g npm
rm -rf node_modules
npm install
gulp
```

**Comment by ghost** [comment]
Just running on Docker with php 7.0.2 - and Upgraded Laravel to 5.2

**Comment by Zemke** [comment]
Perfect, thanks!

**Comment by minhnhat2807** [comment]
Great, thanks
